### ISSUE TITLE
remove your secrets from the file and the git history bro

### ISSUE THREAD

**Issue by I-NOZex** [posva/issue-firebase-nuxt-3#1]
https://github.com/posva/issue-firebase-nuxt-3/blob/9711c454efe0bc0d079d30e1b3a323d50dec635a/plugins/firebase.ts#L9

**Comment by posva** [comment]
Thanks for your concern but the `apiKey` is not secret 😉 

- https://github.com/angular/angularfire/search?q=apiKey
- https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public/37484053#37484053
